export const SECURABLE_NAMES = {
	Home: 'Home',
	PlayerEngagement: 'Dashboard - Player Engagement',
	Marketing: 'Dashboard - Marketing',
	Player: 'Player Management',
	PlayerSearch: 'Player Search',
	ImportPlayerList: 'Import Player List',
	DownloadSearchResult: 'Download Search Result',
	OutputFilterTemplate: 'Output Filter Template',
	PlayerProfile: 'Player Profile',
	UserManagement: 'User Management',
	Teams: 'Teams',
	Roles: 'Roles',
	Users: 'Users',
	System: 'System',
	OperatorAndBrand: 'Operator & Brand',
	CodeList: 'Code List',
	PlayerConfiguration: 'Player Configuration',
	Topic: 'Topic',
	Subtopic: 'Subtopic',
	MessageType: 'Message Type',
	MessageStatus: 'Message Status',
	MessageResponse: 'Message Response',
	FeedbackType: 'Feedback Type',
	FeedbackCategory: 'Feedback Category',
	FeedbackAnswer: 'Feedback Answer',
	SurveyQuestion: 'Survey Question',
	SurveyTemplate: 'Survey Template',
	CaseAndCommunication: 'Case And Communication',
	CampaignSetting: 'Campaign Setting',
	Campaign: 'Campaign Management',
	CampaignWorkspace: 'Campaign Workspace',
	CustomEventSetting: 'Custom Event Setting',
	Segmentation: 'Segmentation',
	ManageCampaign: 'Manage Campaign',
	AgentWorkSpace: 'Agent WorkSpace',
	CallListValidation: 'Call List Validation',
	AgentMonitoring: 'Agent Monitoring',
	CreateCase: 'Create Case',
	ViewCase: 'View Case',
	AddCommunication: 'Add Communication',
	ViewCommunication: 'View Communication',
	EditCommunication: 'Edit Communication',
	CreateSegmentation: 'Create Segmentation',
	ManageSegmentation: 'Manage Segmentation',
	SetSegmentationToStatic: 'Set Segmentation To Static',
	SearchGoalSetting: 'Search Goal Setting',
	UpdateGoalSetting: 'Update Goal Setting',
	ViewGoalSetting: 'View Goal Setting',
	SearchAutoTagging: 'Search Auto Tagging',
	UpdateAutoTagging: 'Update Auto Tagging',
	ViewAutoTagging: 'View Auto Tagging',
	IncentiveGoalSetting: 'Search Incentive Setting',
	UpdateIncentiveSetting: 'Update Incentive Setting',
	ViewIncentiveSetting: 'View Incentive Setting',
	AgentForTagging: 'Agent For Tagging',
	SearchCampaign: 'Search Campaign',
	CreateCampaign: 'Create Campaign',
	EditCampaign: 'Edit Campaign',
	ViewCampaign: 'View Campaign',
	HoldCampaign: 'Hold Campaign',
	ViewOwnPlayers: 'View Own Players',
	ViewAllPlayers: 'View All Players',
	ViewCallListAllPlayers: 'View All Players',
	UpdateAllAgentValidations: 'Update Agent Validations',
	UpdateLeaderValidation: 'Update Leader Validation',
	UpdateCallEvaluation: 'Update Call Evaluation',
	UpdateAgentStatus: 'Update Agent Status',
	UpdateDailyReport: 'Update Daily Report',
	ExportToCSVCallList: 'Export to CSV',
	ExportToCSVAgentWorkSpace: 'Export to CSV',
	ViewContactDetailsLog: 'View Contact Details Log',
	ExportLogtoCSV: 'Export Log to CSV',
	ManageThreshold: 'Manage Threshold',
	CampaignDashboard: 'Campaign Dashboard',
	SurveyAndFeedback: 'Survey And Feedback',
	CampaignPerformance: 'Campaign Performance',
	VIPLevel: 'VIP Level',
	RiskLevel: 'Risk Level',
	PaymentGroup: 'Payment Group',
	PaymentMethod: 'Payment Method',
	Currency: 'Currency',
	MarketingChannel: 'Marketing Channel',
	SignUpPortal: 'Sign Up Portal',
	Language: 'Language',
	PlayerStatus: 'Player Status',
	Country: 'Country',
	RelationshipManagement: 'Relationship Management',
	RemDistribution: 'ReM Distribution',
	RemProfile: 'ReM Profile',
	RemSetting: 'ReM Setting',
	RemHistory: 'ReM History',
	RemAutoDistributionSetting: 'ReM Auto Distribution Setting',
	ManageJourney: 'Manage Journey',
	SearchJourney: 'Search Journey',
	CreateJourney: 'Create Journey',
	EditJourney: 'Edit Journey',
	ViewJourney: 'View Journey',
	SkillMapping: 'Skill Mapping',
	PostChatSurvey: 'Post Chat Survey',
	CaseManagement: 'Case Management',
	CreateCustomerCase: 'Create Case',
	EditCustomerCase: 'Edit Case',
	SearchCaseCommunication: 'Search Case and Communication',
	ViewCustomerCase: 'View Case',
	AddCaseCommunication: 'Add Communication',
	CaseManagementLeaderAccess: 'Case Management Leader Access',
	CreateCaseOnBehalf: 'Create Case on Behalf',
	ReopenCase: 'Reopen Case',
	PCSQuestionnaires: 'PCS Questionnaires',
	CreateCustomQuery: 'Create Custom Query',
	ViewSensitiveData: 'View Sensitive Data',
	CommunicationReview: 'Communication Review',
	CommunicationReviewer: 'Reviewer',
	CommunicationReviewee: 'View All Reviewee',
	CommunicationAnnotation: 'Annotate',
	CommunicationReviewReport: 'Communication Review Report',
	ManageTelegramBot: 'Manage Telegram Bot',
	SearchTelegramBot: 'Search Telegram Bot',
	CreateTelegramBot: 'Create Telegram Bot',
	UpdateTelegramBot: 'Update Telegram Bot',
	ViewTelegramBot: 'View Telegram Bot',
	Broadcast: 'Broadcast',
	CreateBroadcast: 'Create Broadcast',
	EditBroadcast: 'Edit Broadcast',
	ViewBroadcast: 'View Broadcast',
	SearchLeads: 'Search Leads',
	LinkToPlayer: 'Link to Player',
	UnlinkAPlayer: 'Unlink a Player',
	EditLeads: 'Edit Leads',
	RemoveLeads: 'Remove Leads',
	EditLinkedPlayer: 'Edit Linked Player',
	RemoveLinkedPlayer: 'Remove Linked Player',
	Tickets: 'Tickets',
	ManageTickets: 'Manage Tickets',
	MissingDeposit: 'Missing Deposit',
	ReporterRole: 'Reporter Role',
	StaffPerformance: 'Staff Performance',
	CommunicationReviewPeriod: 'Communication Review Period',
	ManagePrimaryFlag: "Manage Primary Flag",
	MissingWithdrawal: "Missing Withdrawal",
	Reporter: "Reporter",
	TicketIssue: "Issue",
	TicketTask: "Task",
	ViewContactDetails: "View Contact Details"
};
