export interface SearchTicketModel {
    ticketType : string,
    ticketID : string,
    summary : string,
    status : string,
    reporter : string,
    assignee : string,
    methodCurrency : string,
    vipGroup : string,
    vipLevel : string,
    userListTeams : string,
    duration : string,
    createdDate : string,
    lastModifiedDate : string,
    lastModifiedBy : string,
    callSign: string,
    ticketTypeId: number,
    statusId: number,
    ticketTypeSequenceId: number,
}