export interface SearchFilterResponseModel {
    createdDateFrom : string,
    createdDateTo : string,
    ticketType : string,
    ticketCode : string,
    summary : string,
    playerUsername : string,
    status : string,
    assignee : string,
    reporter : string,
    externalLinkName : string,
    currency : string,
    vipGroup : string,
    vipLevel : string,
    userListTeams : string,
}