export class DistributionMockResponse {
	public static mockPlayerDistributionPlayerList: any = [
		{
			id: 1,
			playerId: 111,
			userName: 'user_111',
			brandName: 'brand A',
			currencyName: 'PHP',
			vipLevelName: 'Player_One',
			accountStatus: true,
			registrationDate: '2019-11-30T07:26:15.6',
			varianceName: 'Variance A',
		},
		{
			id: 2,
			playerId: 222,
			userName: 'user_222',
			brandName: 'brand B',
			currencyName: 'PHP',
			vipLevelName: 'Player_two',
			accountStatus: true,
			registrationDate: '2019-11-30T07:26:15.6',
			varianceName: 'Variance B',
		},
		{
			id: 4,
			playerId: 444,
			userName: 'user_444',
			brandName: 'brand A',
			currencyName: 'PHP',
			vipLevelName: 'Player_THREE',
			accountStatus: true,
			registrationDate: '2019-11-30T07:26:15.6',
			varianceName: 'Variance A',
		},
		{
			id: 3,
			playerId: 333,
			userName: 'user_333',
			brandName: 'brand B',
			currencyName: 'PHP',
			vipLevelName: 'Player_FOUR',
			accountStatus: true,
			registrationDate: '2019-11-30T07:26:15.6',
			varianceName: 'Variance B',
		},
		{
			id: 5,
			playerId: 555,
			userName: 'user_555',
			brandName: 'brand B',
			currencyName: 'PHP',
			vipLevelName: 'Player_FIVE',
			accountStatus: true,
			registrationDate: '2019-11-30T07:26:15.6',
			varianceName: 'Variance B',
		},
	];
}
