export interface CallValidationListRequestModel {
    campaignId?: number
    playerId?: string
    username?: string
    agentName?: string
    status?: string
    currency?: string
    registrationStartDate?: string
    registrationEndDate?: string
    deposited?: string
    ftdStartAmount?: number
    ftdEndAmount?: number
    ftdStartDate?: string
    ftdEndDate?: string
    taggedStartDate?: string
    taggedEndDate?: string
    primaryGoalReached?: string
    primaryGoalCount?: number
    primaryGoalAmount?: number
    callListNotes?: string
    mobileNumber?: string
    messageStatusAndResponse?: string
    callCaseCreatedStartDate?: string
    callCaseCreatedEndDate?: string
    systemValidation?: string
    agentValidation?: string
    leaderValidation?: string
    leaderJustification?: string
    callEvaluationStartPoint?: number
    callEvaluationEndPoint?: number
    callEvaluationNotes?: string
    highDepositAmount?: string
    agentValidationNotes?: string
    leaderValidationNotes?: string
    pageSize: number
    offsetValue: number
    sortColumn: string
    sortOrder: string
}
